In [ ]:
#Diabetes prediction using SVM(Classification)

SVM-Support vector machine -refer note
1.Data
2.data preprocessing data cleaning,standarization
3.Train-Test Split
4.svm classifier
5.new data it can able to predict

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
import pickle

Data Collectiob ad Analysis

In [ ]:
diabetes_data=pd.read_csv("/content/diabetes (3).csv")
diabetes_data.head()
#1-yes diabetic ,0-no debetic

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
#no of rows and columns
diabetes_data.shape

(768, 9)

In [ ]:
#statistical measures of the data
diabetes_data.describe()#gives the count ,mean ,sd,min,max,etc..

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
#finding the toal number of each type of outcome
diabetes_data['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
diabetes_data.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [ ]:
#seperating the data and labels
X=diabetes_data.drop(columns="Outcome",axis=1);#drop(colums,axis=0 mean we r deleting row,1 mean we r deleting column)
Y=diabetes_data['Outcome'];
print(X);

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

In [ ]:
print(Y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [ ]:
#Standardize the data
scaler=StandardScaler()
scaler.fit(X)

StandardScaler()

#Standardized data contains values only within 0 and 1

In [ ]:
standardized_data=scaler.transform(X);

In [ ]:
print(standardized_data)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

In [ ]:
X=standardized_data;

In [ ]:
#train -test split(4 variables)
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify =Y,random_state=2)
#test_size=20%percent for test
#random_state=means:
# Use seed value 2 for randomization.
# Every time you run the code, you get the same train-test split.


#stratify -ensures that both the test and the train data have better data distribution ,x train-5 yes 5 no y train -2 yes 2 no

In [ ]:
print(X_train.shape,X_test.shape)

(614, 8) (154, 8)

TRAINING THE MODEL

In [ ]:

#Support vector classifier
classifier=svm.SVC(kernel='linear')

In [ ]:
#training the svm
classifier.fit(X_train,Y_train)

SVC(kernel='linear')

In [ ]:
#Model Evaluation
#1.Accuracy Score
#using svm to predict the trained data
X_train_prediction=classifier.predict(X_train)
training_data_Accuracy=accuracy_score(X_train_prediction,Y_train)
print("Accuracy score of the training data :",training_data_Accuracy)

Accuracy score of the training data : 0.7866449511400652

Accuracyy sicore of the test data

In [ ]:
X_test_prediction=classifier.predict(X_test)
test_data_Accuracy=accuracy_score(X_test_prediction,Y_test)
print("Accuracy score of the test data :",test_data_Accuracy)

Accuracy score of the test data : 0.7727272727272727

Making a Predictive system (GIVING A NEW DATA)

> Add blockquote

> Add blockquote

In [ ]:
input_data=(4,110,92,0,0,37.6,0.191,30)
#actual op is o-false lets check the predicted output
#changing the input data to numpy array
input_data_as_numpy_array=np.asarray(input_data)
#reshape the array as we are predicting for one instance
#reason :ore model has 768 examples with 8 columns,but here we are giving only 1 examples soo we r telling 1 row only and this reshaping can be done only on  numpy array .
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)
# for training we gave standardized data ,soo we need to convert this data to standardized data
std_data=scaler.transform(input_data_reshaped)
print(std_data)
prediction=classifier.predict(std_data)#THE OP FROM A MODEL IS A LIST
print("THE OUTCOME IS",prediction)
if(prediction[0]==0):
  print("THE PERSON IS NOT DIABETIC")
else:
  print("THE PERSON IS DIABETIC")

[[ 0.04601433 -0.34096773  1.18359575 -1.28821221 -0.69289057  0.71168975
  -0.84827977 -0.27575966]]
THE OUTCOME IS [0]
THE PERSON IS NOT DIABETIC

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

the op is correct
"

Now we are going to save this training model  in file ,which acts as teh backend

In [ ]:
filename = "diabetes_model.pkl"

pickle.dump(classifier, open(filename, "wb"))

# Explanation:

# pickle.dump() → saves a Python object to a file.
# classifier → your trained SVM model.
# "wb" → write in binary mode.
# diabetes_model.pkl → the file that will be created

In [ ]:
# Download the model from Colab
from google.colab import files

files.download("diabetes_model.pkl")

# After running this, your browser will download:

# diabetes_model.pkl

  WE NOE ONLY SAVED THE MODEL ,BUT WHEN A USER ENTER THE DATA IT NEED TO CONVERTED TO STANDARDIZED VALUE ,in previous file we downloaded only the model not the entire program

In [ ]:
pickle.dump(scaler, open("scaler.pkl", "wb"))
files.download("scaler.pkl")